var superfetch = require('superfetch');
var fs = require('fs');
var path = require('path');

superfetch.get('http://redis.io/commands.json').then(function (res) {
  var contents = '// This file was generated by `$ npm run build` on ' + (new Date()).toLocaleString() + '\n';
  contents += 'module.exports = ' + JSON.stringify(JSON.parse(res), null, '  ') + ';\n';
  fs.writeFile(path.join(__dirname, '..', 'index.js'), contents);
}).catch(function (err) {
  console.error(err);
});
